---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-api
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: ui-api
        image: img:latest
        imagePullPolicy: Always
        env:
        - name: MONGODB_HOST
          value: "mongodb.l6p.svc.cluster.local:27017"
        - name: MONGODB_USER
          value: "root"
        - name: MONGODB_PASS
          value: "rootpassword"
        ports:
        - name: http
          containerPort: 1323
          protocol: TCP
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          httpGet:
            path: /api/v1/ping
            port: http
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          httpGet:
            path: /api/v1/ping
            port: http
        resources:
          requests:
            cpu: 0.5
            memory: 512Mi
      serviceAccountName: ui-api
      terminationGracePeriodSeconds: 10
