# Adds namespace to all resources.
namespace: default

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: l6p-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

resources:
- deployment.yaml
- service.yaml
- service_account.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: api
  newName: localhost:32000/api
  newTag: latest
